### PR TITLE
Support for Symfony 4 and PHP 7.1

### PR DESCRIPTION
**Pull request by fre5h**
Waiting for version of `vich/uploader-bundle` which will work with Symfony 4.0

### CODE REVIEW

**Comment by Bukashk0zzz** [comment]
vich/uploader-bundle 1.7 now have symfony 4 support. can you please restart your build.

**Comment by fre5h** [comment]
@Bukashk0zzz Do you mean `1.7.x-dev`? Because there is no stable 1.7.0

**Comment by Bukashk0zzz** [comment]
@fre5h yes.

**Comment by fre5h** [comment]
@Bukashk0zzz I am waiting for stable 1.7.0 release

**Comment by fre5h** [comment]
@Bukashk0zzz Take and check `v2.0.0` please :)

**Comment by Bukashk0zzz** [comment]
@fre5h thanks

**Pull request merged**
