### PR TITLE
Fix issue with serialization of proxy objects

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
add test and all staff. If you have time please merge and create new tag. thanks.

### CODE REVIEW

**Comment by fre5h** [comment]
Travis says: code style is broken :)

**Comment by Bukashk0zzz** [comment]
Fixed.

**Comment by Bukashk0zzz** [comment]
now all tests ok.

**Comment by fre5h** [comment]
Merry Christmas!

**Comment by Bukashk0zzz** [comment]
Thanks.

**Pull request merged**
