### PR TITLE
fix issue with port in url

### PR DESCRIPTION
**Pull request by Bukashk0zzz**
Add port to url. 
Fix problem with urls looks like this http://127.0.0.1:8000/img/test.png

### CODE REVIEW

**Comment by fre5h** [comment]
@Bukashk0zzz please update tests for new use cases, all new `if` statements should be covered with tests.

**Comment by Bukashk0zzz** [comment]
ok. will add tests today/tomorrow.

**Comment by fre5h** [comment]
Or you can change the destination branch of this PR to `develop` and I can add missed tests by myself. I've just created a new branch `develop`.

**Comment by Bukashk0zzz** [comment]
I added tests. Can you please merge my request. And create stable tag. 

Thanks.

**Comment by fre5h** [comment]
@Bukashk0zzz Nice work, thanks

**Comment by fre5h** [comment]
@Bukashk0zzz v1.0.3 take it (maybe it will take few minutes for autoupdate on packagist)

**Pull request merged**
